{{- if .Values.opentelemetry.enabled -}}
{{- $defaultEndpoint := "http://otel-collector.monitoring.svc:4317" -}}
{{- if eq .Values.opentelemetry.type "nodejs" -}}
  {{- $defaultEndpoint = "http://otel-collector.monitoring.svc:4318" -}}
{{- end -}}

{{- $finalEndpoint := .Values.opentelemetry.endpoint | default $defaultEndpoint -}}

apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  exporter:
    endpoint: {{ $finalEndpoint }}
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: {{ .Values.opentelemetry.samplerRatio | quote }}
  
  {{- if eq .Values.opentelemetry.type "nodejs" }}
  nodejs:
    image: {{ .Values.opentelemetry.images.nodejs }}
  {{- else if eq .Values.opentelemetry.type "java" }}
  java:
    image: {{ .Values.opentelemetry.images.java }}
  {{- else if eq .Values.opentelemetry.type "python" }}
  python:
    image: {{ .Values.opentelemetry.images.python }}
  {{- else if eq .Values.opentelemetry.type "dotnet" }}
  dotnet:
    image: {{ .Values.opentelemetry.images.dotnet }}
  {{- end }}
{{- end -}}