{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "generic.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  - {{ .Values.istio.gateway }}
  hosts:
  - {{ required "istio.host é obrigatório quando istio.enabled=true" .Values.istio.host }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "generic.fullname" . }}
        port:
          number: {{ .Values.istio.destinationPort }}
{{- end }}
